version: '3.8'

services:

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: events_db
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: always

volumes:
  clickhouse_data:
